FROM node:20.12.2

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli@17.3.5

RUN npm install

COPY . .

RUN ng build

EXPOSE 4211

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4211"]

